- alias: Arm home - away
  trigger:
    - platform: state
      entity_id: 'device_tracker.aindrila_location'
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: 'device_tracker.soumalya_location'
      from: 'home'
      to: 'not_home'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'device_tracker.aindrila_location'
          state: 'not_home'
        - condition: state
          entity_id: 'device_tracker.soumalya_location'
          state: 'not_home'
  action:
    service: ifttt.trigger
    data: {"event":"arm_away"}
    
- alias: Disarm home
  trigger:
    - platform: state
      entity_id: 'device_tracker.aindrila_location'
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: 'device_tracker.soumalya_location'
      from: 'not_home'
      to: 'home'
#  condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: 'device_tracker.aindrila_location'
#          state: 'not_home'
#        - condition: state
#          entity_id: 'device_tracker.soumalya_location'
#          state: 'not_home'
  action:
    service: ifttt.trigger
    data: {"event":"disarm_home"}
    
- alias: Arm home - home
  trigger:
    - platform: time
      at: '23:30:00'      
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'device_tracker.aindrila_location'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.soumalya_location'
          state: 'home'
  action:
    service: ifttt.trigger
    data: {"event":"arm_home"}