#- alias: Soumalya reached home
#  trigger:
#    platform: state
#    entity_id: device_tracker.988673494733504852
#    from: not_home
#    to: home    
#  action:
#    service: ifttt.trigger
#    data: {"event":"disarm_home"}   
   
#- alias: Aindrila reached home
#  trigger:
#    platform: state
#    entity_id: device_tracker.zy2232bblf
#    from: not_home
#    to: home    
#  action:
#    service: ifttt.trigger
#    data: {"event":"disarm_home"}  

#- alias: Aindrila reached university
#  trigger:
#    platform: state
#    entity_id: device_tracker.aindrila_phone
#    to: University
#  action:
#    service: ifttt.trigger
#    data: {"event":"TestHA_Trigger", "value1":"Aindrila reached university"}

- alias: Arm home - away
  trigger:
    - platform: state
      entity_id: device_tracker.aindrila_location
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.soumalya_location
      from: 'home'
      to: 'not_home'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.aindrila_location
          state: 'not_home'
        - condition: state
          entity_id: device_tracker.soumalya_location
          state: 'not_home'
  action:
    service: ifttt.trigger
    data: {"event":"arm_away"}
    
- alias: Disarm home
  trigger:
    - platform: state
      entity_id: device_tracker.aindrila_location
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.soumalya_location
      from: 'not_home'
      to: 'home'
#  condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: device_tracker.aindrila_location
#          state: 'not_home'
#        - condition: state
#          entity_id: device_tracker.soumalya_location
#          state: 'not_home'
  action:
    service: ifttt.trigger
    data: {"event":"disarm_home"}
    
- alias: Arm home - home
  trigger:
    - platform: time
      after: '23:30:00'      
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.aindrila_location
          state: 'home'
        - condition: state
          entity_id: device_tracker.soumalya_location
          state: 'home'
  action:
    service: ifttt.trigger
    data: {"event":"arm_home"}